# **`Python Pandas Exercise on Automobile_data.csv`**

In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [5]:
df = pd.read_csv('Automobile_data.csv')

### From the given dataset print the first and last five rows

In [6]:
df.head()

,index,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
0,0,alfa-romero,convertible,88.6,168.8,dohc,four,111,21,13495.0
1,1,alfa-romero,convertible,88.6,168.8,dohc,four,111,21,16500.0
2,2,alfa-romero,hatchback,94.5,171.2,ohcv,six,154,19,16500.0
3,3,audi,sedan,99.8,176.6,ohc,four,102,24,13950.0
4,4,audi,sedan,99.4,176.6,ohc,five,115,18,17450.0

In [7]:
df.tail()

,index,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
56,81,volkswagen,sedan,97.3,171.7,ohc,four,85,27,7975.0
57,82,volkswagen,sedan,97.3,171.7,ohc,four,52,37,7995.0
58,86,volkswagen,sedan,97.3,171.7,ohc,four,100,26,9995.0
59,87,volvo,sedan,104.3,188.8,ohc,four,114,23,12940.0
60,88,volvo,wagon,104.3,188.8,ohc,four,114,23,13415.0

## Clean the dataset and update the CSV file


*   Replace all column values which contain ?, n.a, or NaN.

In [8]:
# replace all column values which contain ?, n.a, or NaN.
import numpy as np
df.replace(['?', 'n.a', 'NaN'], 0).isna().sum()

index               0
company             0
body-style          0
wheel-base          0
length              0
engine-type         0
num-of-cylinders    0
horsepower          0
average-mileage     0
price               3
dtype: int64

### Find the most expensive car company name
Print most expensive car’s company name and price.

In [9]:
df1 = df.sort_values(by=['price'], ascending=False).head(1)
df1[['company','price']]

          company    price
35  mercedes-benz  45400.0

In [10]:
df.loc[df['price']==df['price'].max(), ['company', 'price']]

          company    price
35  mercedes-benz  45400.0

In [11]:
 df['price'].max()

45400.0

## Print All Toyota Cars details

In [12]:
df2 = df.query('company=="toyota"')
df2

,index,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
48,66,toyota,hatchback,95.7,158.7,ohc,four,62,35,5348.0
49,67,toyota,hatchback,95.7,158.7,ohc,four,62,31,6338.0
50,68,toyota,hatchback,95.7,158.7,ohc,four,62,31,6488.0
51,69,toyota,wagon,95.7,169.7,ohc,four,62,31,6918.0
52,70,toyota,wagon,95.7,169.7,ohc,four,62,27,7898.0
53,71,toyota,wagon,95.7,169.7,ohc,four,62,27,8778.0
54,79,toyota,wagon,104.5,187.8,dohc,six,156,19,15750.0

## Count total cars per company

In [13]:
df['company'].value_counts()

company
toyota           7
bmw              6
mazda            5
nissan           5
audi             4
mercedes-benz    4
mitsubishi       4
volkswagen       4
alfa-romero      3
chevrolet        3
honda            3
isuzu            3
jaguar           3
porsche          3
dodge            2
volvo            2
Name: count, dtype: int64

In [14]:
df.groupby('company').size()

company
alfa-romero      3
audi             4
bmw              6
chevrolet        3
dodge            2
honda            3
isuzu            3
jaguar           3
mazda            5
mercedes-benz    4
mitsubishi       4
nissan           5
porsche          3
toyota           7
volkswagen       4
volvo            2
dtype: int64

## Find each company’s Higesht price car

In [15]:
df3 = df.loc[df.groupby('company')['price'].idxmax() , ['company', 'price']]
df3

          company    price
1     alfa-romero  16500.0
6            audi  18920.0
11            bmw  41315.0
15      chevrolet   6575.0
16          dodge   6377.0
19          honda  12945.0
21          isuzu   6785.0
26         jaguar  36000.0
31          mazda  18344.0
35  mercedes-benz  45400.0
39     mitsubishi   8189.0
44         nissan  13499.0
46        porsche  37028.0
54         toyota  15750.0
58     volkswagen   9995.0
60          volvo  13415.0

## Find the average mileage of each car making company

In [26]:
df4 = df.groupby('company')['average-mileage'].mean().reset_index()
df4.columns = ['company', 'average-mileage']
df4

          company  average-mileage
0     alfa-romero        20.333333
1            audi        20.000000
2             bmw        19.000000
3       chevrolet        41.000000
4           dodge        31.000000
5           honda        26.333333
6           isuzu        33.333333
7          jaguar        14.333333
8           mazda        28.000000
9   mercedes-benz        18.000000
10     mitsubishi        29.500000
11         nissan        31.400000
12        porsche        17.000000
13         toyota        28.714286
14     volkswagen        31.750000
15          volvo        23.000000

## Sort all cars by Price column

In [29]:
df.sort_values(by='price', ascending=False)

,index,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
35,47,mercedes-benz,hardtop,112.0,199.2,ohcv,eight,184,14,45400.0
11,14,bmw,sedan,103.5,193.8,ohc,six,182,16,41315.0
34,46,mercedes-benz,sedan,120.9,208.1,ohcv,eight,184,14,40960.0
46,62,porsche,convertible,89.5,168.9,ohcf,six,207,17,37028.0
12,15,bmw,sedan,110.0,197.0,ohc,six,182,15,36880.0
...,...,...,...,...,...,...,...,...,...,...
27,36,mazda,hatchback,93.1,159.1,ohc,four,68,30,5195.0
13,16,chevrolet,hatchback,88.4,141.1,l,three,48,47,5151.0
22,31,isuzu,sedan,94.5,155.9,ohc,four,70,38,NaN
23,32,isuzu,sedan,94.5,155.9,ohc,four,70,38,NaN
47,63,porsche,hatchback,98.4,175.7,dohcv,eight,288,17,NaN

## Concatenate two data frames using the following conditions
**Create two data frames using the following two dictionaries.**

GermanCars = {'Company': ['Ford', 'Mercedes', 'BMV', 'Audi'], 'Price': [23845, 171995, 135925 , 71400]}

japaneseCars = {'Company': ['Toyota', 'Honda', 'Nissan', 'Mitsubishi '], 'Price': [29995, 23600, 61500 , 58900]}

In [42]:
germanCars = {'Company': ['Ford', 'Mercedes', 'BMV', 'Audi'], 'price': [23845, 171995, 135925 , 71400]}
japaneseCars = {'Company': ['Toyota', 'Honda', 'Nissan', 'Mitsubishi '], 'price': [29995, 23600, 61500 , 58900]}
cars_df1 = pd.DataFrame(germanCars)
cars_df2 = pd.DataFrame(japaneseCars)

In [43]:
cars_df1['origin_city'] = ['jermany' if i == 0 else '' for i in range(len(cars_df1))]
cars_df2['origin_city'] = ['japan' if i == 0 else '' for i in range(len(cars_df2))]

In [54]:
cars_df = pd.concat([cars_df1, cars_df2])
cars_df = cars_df[['origin_city', 'Company', 'price']]
cars_df.columns = ['', 'company', 'price']
cars_df

                company   price
0  jermany         Ford   23845
1              Mercedes  171995
2                   BMV  135925
3                  Audi   71400
0    japan       Toyota   29995
1                 Honda   23600
2                Nissan   61500
3           Mitsubishi    58900

## Merge two data frames using the following condition
Create two data frames using the following two Dicts, Merge two data frames, and append the second data frame as a new column to the first data frame.

Car_Price = {'Company': ['Toyota', 'Honda', 'BMV', 'Audi'], 'Price': [23845, 17995, 135925 , 71400]}
car_Horsepower = {'Company': ['Toyota', 'Honda', 'BMV', 'Audi'], 'horsepower': [141, 80, 182 , 160]}

In [57]:
car_price = {'company': ['Toyota', 'Honda', 'BMV', 'Audi'], 'price': [23845, 17995, 135925 , 71400]}
car_horsepower = {'company': ['Toyota', 'Honda', 'BMV', 'Audi'], 'horsepower': [141, 80, 182 , 160]}
df_price = pd.DataFrame(car_price)
df_hp = pd.DataFrame(car_horsepower)
df_5 = pd.merge(df_price, df_hp, on='company')
df_5

  company   price  horsepower
0  Toyota   23845         141
1   Honda   17995          80
2     BMV  135925         182
3    Audi   71400         160